export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const FILTER_SERVICE = "FILTER_SERVICE";
export const FILTER_SERVICE_FIELD = "FILTER_SERVICE_FIELD";
export const EDIT_SERVICE_FIELD = "EDIT_SERVICE_FIELD";
export const SAVE_EDIT_FIELD = "SAVE_EDIT_FIELD";
export const CHANGE_EDIT_STATUS = "CHANGE_EDIT_STATUS";
